// Real tracked data from vault /Users/mac/vaults/#Bwell/
// Sources: 602/04_Blood_Work.md, 603/01_Profile.md, 603/02_Blood_Work.md, 603/03_Biometrics.md

import type { Metric, MetricCategory } from "../types/metrics";

// Milestone schedule (quarterly DEXA + blood work)
export const MILESTONES = {
  M1: "2025-02-06T12:00:00.000Z", // Feb 2025 - Baseline
  M2: "2025-05-01T12:00:00.000Z", // May 2025 - Q2
  M3: "2025-09-04T12:00:00.000Z", // Sep 2025 - Q3
  M4: "2026-01-15T12:00:00.000Z", // Jan 2026 - Current (cessation Day 23)
  M5: "2026-04-01T12:00:00.000Z", // Apr 2026 - Q1 Target (cessation Day 100)
  M6: "2026-07-01T12:00:00.000Z", // Jul 2026 - Q2 Stretch
  CURRENT: "2026-01-15T12:00:00.000Z",
} as const;

export const MILESTONE_INFO: Record<string, { label: string; description: string }> = {
  M1: { label: "M1", description: "Feb 2025 - Baseline" },
  M2: { label: "M2", description: "May 2025" },
  M3: { label: "M3", description: "Sep 2025" },
  M4: { label: "M4", description: "Jan 2026 - Current" },
  M5: { label: "M5", description: "Apr 2026 - Q1 Target" },
  M6: { label: "M6", description: "Jul 2026 - Q2 Stretch" },
};

// 2026 Targets from 08_Reference.md
export interface MetricTarget {
  metricName: string;
  q1Target: number; // M5 - Apr 2026
  q2Stretch: number; // M6 - Jul 2026
  unit: string;
  direction: "higher" | "lower" | "target";
}

export const METRIC_TARGETS: MetricTarget[] = [
  // Body Composition
  { metricName: "Body Fat", q1Target: 21.5, q2Stretch: 19.5, unit: "%", direction: "lower" },
  { metricName: "Lean Mass", q1Target: 168, q2Stretch: 170, unit: "lbs", direction: "higher" },
  { metricName: "Visceral Fat (VAT)", q1Target: 650, q2Stretch: 600, unit: "g", direction: "lower" },
  { metricName: "Weight", q1Target: 205, q2Stretch: 200, unit: "lbs", direction: "target" },

  // Hormones
  { metricName: "Total Testosterone", q1Target: 550, q2Stretch: 600, unit: "ng/dL", direction: "higher" },

  // Vitamins (normalize excess)
  { metricName: "Vitamin B6 (P5P)", q1Target: 40, q2Stretch: 35, unit: "μg/L", direction: "lower" },
  { metricName: "Biotin", q1Target: 3, q2Stretch: 2, unit: "ng/mL", direction: "lower" },

  // Lipids
  { metricName: "LDL-C", q1Target: 100, q2Stretch: 90, unit: "mg/dL", direction: "lower" },
  { metricName: "HDL-C", q1Target: 50, q2Stretch: 55, unit: "mg/dL", direction: "higher" },

  // Inflammatory
  { metricName: "Homocysteine", q1Target: 8, q2Stretch: 7, unit: "μmol/L", direction: "lower" },

  // Metabolic
  { metricName: "eGFR", q1Target: 85, q2Stretch: 90, unit: "mL/min", direction: "higher" },

  // Metabolic (additional)
  { metricName: "Glucose", q1Target: 82, q2Stretch: 80, unit: "mg/dL", direction: "target" },
  { metricName: "Creatinine", q1Target: 1.0, q2Stretch: 0.95, unit: "mg/dL", direction: "lower" },

  // Vitamins (maintain optimal)
  { metricName: "Vitamin D", q1Target: 50, q2Stretch: 55, unit: "ng/mL", direction: "target" },
  { metricName: "Zinc", q1Target: 85, q2Stretch: 90, unit: "μg/dL", direction: "target" },

  // Lipids (additional)
  { metricName: "Total Cholesterol", q1Target: 170, q2Stretch: 165, unit: "mg/dL", direction: "target" },
  { metricName: "Triglycerides", q1Target: 75, q2Stretch: 70, unit: "mg/dL", direction: "lower" },

  // Hormones (additional)
  { metricName: "Cortisol (AM)", q1Target: 12, q2Stretch: 14, unit: "μg/dL", direction: "target" },
  { metricName: "TSH", q1Target: 2.0, q2Stretch: 1.8, unit: "μIU/mL", direction: "target" },

  // Hematology
  { metricName: "Hemoglobin", q1Target: 14.5, q2Stretch: 15.0, unit: "g/dL", direction: "higher" },
  { metricName: "Hematocrit", q1Target: 43, q2Stretch: 44, unit: "%", direction: "higher" },

  // Autonomic (WHOOP)
  { metricName: "HRV (RMSSD)", q1Target: 45, q2Stretch: 48, unit: "ms", direction: "higher" },
  { metricName: "Recovery Score", q1Target: 75, q2Stretch: 80, unit: "%", direction: "higher" },
  { metricName: "Resting Heart Rate", q1Target: 54, q2Stretch: 53, unit: "BPM", direction: "lower" },
  { metricName: "Sleep Duration", q1Target: 7.5, q2Stretch: 7.75, unit: "hrs", direction: "higher" },
];

// Helper to get targets for a specific metric
export function getMetricTargets(metricName: string): MetricTarget | undefined {
  return METRIC_TARGETS.find((t) => t.metricName === metricName);
}

// Generate projection data points for a metric
export function getProjections(
  metricName: string
): Array<{ timestamp: string; value: number; isProjection: true; label: string }> {
  const target = getMetricTargets(metricName);
  if (!target) return [];

  return [
    {
      timestamp: MILESTONES.M5,
      value: target.q1Target,
      isProjection: true,
      label: "M5",
    },
    {
      timestamp: MILESTONES.M6,
      value: target.q2Stretch,
      isProjection: true,
      label: "M6",
    },
  ];
}

// Real blood work data from May 2025 (M2)
export const realBloodWorkM2: Metric[] = [
  // Metabolic Panel
  {
    id: "metabolic-glucose-m2",
    name: "Glucose",
    value: 82,
    unit: "mg/dL",
    category: "metabolic",
    subcategory: "glucose" as any,
    timestamp: MILESTONES.M2,
    improvement: "target range",
    referenceRange: { min: 70, max: 100 },
    optimalRange: { min: 75, max: 90 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "metabolic-hba1c-m2",
    name: "HbA1c",
    value: 5.2,
    unit: "%",
    category: "metabolic",
    subcategory: "glucose" as any,
    timestamp: MILESTONES.M2,
    improvement: "lower is better",
    referenceRange: { min: 4.0, max: 5.7 },
    optimalRange: { min: 4.5, max: 5.3 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "metabolic-insulin-m2",
    name: "Fasting Insulin",
    value: 5.7,
    unit: "μIU/mL",
    category: "metabolic",
    subcategory: "glucose" as any,
    timestamp: MILESTONES.M2,
    improvement: "lower is better",
    referenceRange: { min: 2, max: 20 },
    optimalRange: { min: 2, max: 8 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "metabolic-creatinine-m2",
    name: "Creatinine",
    value: 1.18,
    unit: "mg/dL",
    category: "metabolic",
    subcategory: "kidney" as any,
    timestamp: MILESTONES.M2,
    improvement: "target range",
    referenceRange: { min: 0.7, max: 1.3 },
    optimalRange: { min: 0.7, max: 1.1 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "metabolic-egfr-m2",
    name: "eGFR",
    value: 78,
    unit: "mL/min",
    category: "metabolic",
    subcategory: "kidney" as any,
    timestamp: MILESTONES.M2,
    improvement: "higher is better",
    referenceRange: { min: 60, max: 120 },
    optimalRange: { min: 90, max: 120 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "metabolic-bun-m2",
    name: "BUN",
    value: 20.0,
    unit: "mg/dL",
    category: "metabolic",
    subcategory: "kidney" as any,
    timestamp: MILESTONES.M2,
    improvement: "target range",
    referenceRange: { min: 7, max: 20 },
    optimalRange: { min: 10, max: 18 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },

  // Lipid Panel
  {
    id: "lipids-total-chol-m2",
    name: "Total Cholesterol",
    value: 175,
    unit: "mg/dL",
    category: "lipids",
    subcategory: "cholesterol" as any,
    timestamp: MILESTONES.M2,
    improvement: "target range",
    referenceRange: { min: 125, max: 200 },
    optimalRange: { min: 140, max: 180 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "lipids-hdl-m2",
    name: "HDL-C",
    value: 43,
    unit: "mg/dL",
    category: "lipids",
    subcategory: "cholesterol" as any,
    timestamp: MILESTONES.M2,
    improvement: "higher is better",
    referenceRange: { min: 40, max: 100 },
    optimalRange: { min: 50, max: 80 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "lipids-ldl-m2",
    name: "LDL-C",
    value: 115,
    unit: "mg/dL",
    category: "lipids",
    subcategory: "cholesterol" as any,
    timestamp: MILESTONES.M2,
    improvement: "lower is better",
    referenceRange: { min: 0, max: 130 },
    optimalRange: { min: 0, max: 100 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "lipids-trig-m2",
    name: "Triglycerides",
    value: 86,
    unit: "mg/dL",
    category: "lipids",
    subcategory: "triglycerides" as any,
    timestamp: MILESTONES.M2,
    improvement: "lower is better",
    referenceRange: { min: 0, max: 150 },
    optimalRange: { min: 0, max: 100 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },

  // Vitamins
  {
    id: "vitamins-d-m2",
    name: "Vitamin D",
    value: 48.43,
    unit: "ng/mL",
    category: "vitamins",
    subcategory: "fat-soluble" as any,
    timestamp: MILESTONES.M2,
    improvement: "target range",
    referenceRange: { min: 30, max: 100 },
    optimalRange: { min: 40, max: 60 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "vitamins-b12-m2",
    name: "Vitamin B12",
    value: 678,
    unit: "pg/mL",
    category: "vitamins",
    subcategory: "b-vitamins" as any,
    timestamp: MILESTONES.M2,
    improvement: "target range",
    referenceRange: { min: 200, max: 900 },
    optimalRange: { min: 400, max: 800 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "vitamins-folate-m2",
    name: "Folate",
    value: 16.2,
    unit: "ng/mL",
    category: "vitamins",
    subcategory: "b-vitamins" as any,
    timestamp: MILESTONES.M2,
    improvement: "target range",
    referenceRange: { min: 3, max: 25 },
    optimalRange: { min: 10, max: 20 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "vitamins-b6-m2",
    name: "Vitamin B6 (P5P)",
    value: 102.9,
    unit: "μg/L",
    category: "vitamins",
    subcategory: "b-vitamins" as any,
    timestamp: MILESTONES.M2,
    improvement: "target range",
    referenceRange: { min: 5, max: 50 },
    optimalRange: { min: 20, max: 50 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "vitamins-biotin-m2",
    name: "Biotin",
    value: 7.78,
    unit: "ng/mL",
    category: "vitamins",
    subcategory: "b-vitamins" as any,
    timestamp: MILESTONES.M2,
    improvement: "target range",
    referenceRange: { min: 0.1, max: 4.0 },
    optimalRange: { min: 0.5, max: 2.0 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },

  // Minerals
  {
    id: "minerals-zinc-m2",
    name: "Zinc",
    value: 89,
    unit: "μg/dL",
    category: "minerals",
    subcategory: "essential" as any,
    timestamp: MILESTONES.M2,
    improvement: "target range",
    referenceRange: { min: 60, max: 120 },
    optimalRange: { min: 70, max: 100 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "minerals-copper-m2",
    name: "Copper",
    value: 104,
    unit: "μg/dL",
    category: "minerals",
    subcategory: "essential" as any,
    timestamp: MILESTONES.M2,
    improvement: "target range",
    referenceRange: { min: 70, max: 175 },
    optimalRange: { min: 80, max: 140 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "minerals-magnesium-m2",
    name: "Magnesium (RBC)",
    value: 6.7,
    unit: "mg/dL",
    category: "minerals",
    subcategory: "essential" as any,
    timestamp: MILESTONES.M2,
    improvement: "target range",
    referenceRange: { min: 4.2, max: 6.8 },
    optimalRange: { min: 5.5, max: 6.5 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },

  // Inflammatory
  {
    id: "inflammatory-homocysteine-m2",
    name: "Homocysteine",
    value: 9.4,
    unit: "μmol/L",
    category: "inflammatory",
    subcategory: "homocysteine" as any,
    timestamp: MILESTONES.M2,
    improvement: "lower is better",
    referenceRange: { min: 5, max: 15 },
    optimalRange: { min: 5, max: 8 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },

  // Hormones
  {
    id: "hormones-total-t-m2",
    name: "Total Testosterone",
    value: 470,
    unit: "ng/dL",
    category: "hormones",
    subcategory: "sex" as any,
    timestamp: MILESTONES.M2,
    improvement: "higher is better",
    referenceRange: { min: 300, max: 1000 },
    optimalRange: { min: 500, max: 800 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "hormones-cortisol-m2",
    name: "Cortisol (AM)",
    value: 9.09,
    unit: "μg/dL",
    category: "hormones",
    subcategory: "cortisol" as any,
    timestamp: MILESTONES.M2,
    improvement: "target range",
    referenceRange: { min: 6.2, max: 19.4 },
    optimalRange: { min: 10, max: 18 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "hormones-tsh-m2",
    name: "TSH",
    value: 2.30,
    unit: "μIU/mL",
    category: "hormones",
    subcategory: "thyroid" as any,
    timestamp: MILESTONES.M2,
    improvement: "target range",
    referenceRange: { min: 0.4, max: 4.0 },
    optimalRange: { min: 1.0, max: 2.5 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "hormones-freet4-m2",
    name: "Free T4",
    value: 1.28,
    unit: "ng/dL",
    category: "hormones",
    subcategory: "thyroid" as any,
    timestamp: MILESTONES.M2,
    improvement: "target range",
    referenceRange: { min: 0.8, max: 1.8 },
    optimalRange: { min: 1.0, max: 1.5 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "hormones-freet3-m2",
    name: "Free T3",
    value: 3.40,
    unit: "pg/mL",
    category: "hormones",
    subcategory: "thyroid" as any,
    timestamp: MILESTONES.M2,
    improvement: "target range",
    referenceRange: { min: 2.3, max: 4.2 },
    optimalRange: { min: 2.8, max: 3.8 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "hormones-dheas-m2",
    name: "DHEA-S",
    value: 256,
    unit: "μg/dL",
    category: "hormones",
    subcategory: "sex" as any,
    timestamp: MILESTONES.M2,
    improvement: "target range",
    referenceRange: { min: 100, max: 500 },
    optimalRange: { min: 250, max: 400 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },

  // Hematology
  {
    id: "hematology-wbc-m2",
    name: "WBC",
    value: 5.3,
    unit: "K/μL",
    category: "hematology",
    subcategory: "wbc" as any,
    timestamp: MILESTONES.M2,
    improvement: "target range",
    referenceRange: { min: 4.5, max: 11 },
    optimalRange: { min: 4.5, max: 7.5 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "hematology-rbc-m2",
    name: "RBC",
    value: 4.15,
    unit: "M/μL",
    category: "hematology",
    subcategory: "cbc" as any,
    timestamp: MILESTONES.M2,
    improvement: "target range",
    referenceRange: { min: 4.5, max: 5.9 },
    optimalRange: { min: 4.5, max: 5.5 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "hematology-hemoglobin-m2",
    name: "Hemoglobin",
    value: 13.7,
    unit: "g/dL",
    category: "hematology",
    subcategory: "hemoglobin" as any,
    timestamp: MILESTONES.M2,
    improvement: "target range",
    referenceRange: { min: 13.5, max: 17.5 },
    optimalRange: { min: 14.0, max: 16.5 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "hematology-hematocrit-m2",
    name: "Hematocrit",
    value: 41.2,
    unit: "%",
    category: "hematology",
    subcategory: "cbc" as any,
    timestamp: MILESTONES.M2,
    improvement: "target range",
    referenceRange: { min: 38, max: 50 },
    optimalRange: { min: 42, max: 48 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "hematology-platelets-m2",
    name: "Platelets",
    value: 205,
    unit: "K/μL",
    category: "hematology",
    subcategory: "platelets" as any,
    timestamp: MILESTONES.M2,
    improvement: "target range",
    referenceRange: { min: 150, max: 400 },
    optimalRange: { min: 200, max: 300 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
];

// M1 Baseline Blood Work (Feb 2025) - from vault analysis_M2_metrics.md
export const realBloodWorkM1: Metric[] = [
  // Metabolic Panel
  {
    id: "metabolic-glucose-m1",
    name: "Glucose",
    value: 103,
    unit: "mg/dL",
    category: "metabolic",
    subcategory: "glucose" as any,
    timestamp: MILESTONES.M1,
    improvement: "target range",
    referenceRange: { min: 70, max: 100 },
    optimalRange: { min: 75, max: 90 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "metabolic-creatinine-m1",
    name: "Creatinine",
    value: 0.99,
    unit: "mg/dL",
    category: "metabolic",
    subcategory: "kidney" as any,
    timestamp: MILESTONES.M1,
    improvement: "target range",
    referenceRange: { min: 0.7, max: 1.3 },
    optimalRange: { min: 0.7, max: 1.1 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "metabolic-egfr-m1",
    name: "eGFR",
    value: 96,
    unit: "mL/min",
    category: "metabolic",
    subcategory: "kidney" as any,
    timestamp: MILESTONES.M1,
    improvement: "higher is better",
    referenceRange: { min: 60, max: 120 },
    optimalRange: { min: 90, max: 120 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "metabolic-bun-m1",
    name: "BUN",
    value: 21.0,
    unit: "mg/dL",
    category: "metabolic",
    subcategory: "kidney" as any,
    timestamp: MILESTONES.M1,
    improvement: "target range",
    referenceRange: { min: 7, max: 20 },
    optimalRange: { min: 10, max: 18 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },

  // Lipid Panel
  {
    id: "lipids-total-chol-m1",
    name: "Total Cholesterol",
    value: 137,
    unit: "mg/dL",
    category: "lipids",
    subcategory: "cholesterol" as any,
    timestamp: MILESTONES.M1,
    improvement: "target range",
    referenceRange: { min: 125, max: 200 },
    optimalRange: { min: 140, max: 180 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "lipids-hdl-m1",
    name: "HDL-C",
    value: 37,
    unit: "mg/dL",
    category: "lipids",
    subcategory: "cholesterol" as any,
    timestamp: MILESTONES.M1,
    improvement: "higher is better",
    referenceRange: { min: 40, max: 100 },
    optimalRange: { min: 50, max: 80 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "lipids-ldl-m1",
    name: "LDL-C",
    value: 87,
    unit: "mg/dL",
    category: "lipids",
    subcategory: "cholesterol" as any,
    timestamp: MILESTONES.M1,
    improvement: "lower is better",
    referenceRange: { min: 0, max: 130 },
    optimalRange: { min: 0, max: 100 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "lipids-trig-m1",
    name: "Triglycerides",
    value: 65,
    unit: "mg/dL",
    category: "lipids",
    subcategory: "triglycerides" as any,
    timestamp: MILESTONES.M1,
    improvement: "lower is better",
    referenceRange: { min: 0, max: 150 },
    optimalRange: { min: 0, max: 100 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },

  // Vitamins
  {
    id: "vitamins-d-m1",
    name: "Vitamin D",
    value: 26.78,
    unit: "ng/mL",
    category: "vitamins",
    subcategory: "fat-soluble" as any,
    timestamp: MILESTONES.M1,
    improvement: "target range",
    referenceRange: { min: 30, max: 100 },
    optimalRange: { min: 40, max: 60 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "vitamins-b6-m1",
    name: "Vitamin B6 (P5P)",
    value: 20.3,
    unit: "μg/L",
    category: "vitamins",
    subcategory: "b-vitamins" as any,
    timestamp: MILESTONES.M1,
    improvement: "target range",
    referenceRange: { min: 5, max: 50 },
    optimalRange: { min: 20, max: 50 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "vitamins-biotin-m1",
    name: "Biotin",
    value: 0.31,
    unit: "ng/mL",
    category: "vitamins",
    subcategory: "b-vitamins" as any,
    timestamp: MILESTONES.M1,
    improvement: "target range",
    referenceRange: { min: 0.1, max: 4.0 },
    optimalRange: { min: 0.5, max: 2.0 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },

  // Minerals
  {
    id: "minerals-zinc-m1",
    name: "Zinc",
    value: 63,
    unit: "μg/dL",
    category: "minerals",
    subcategory: "essential" as any,
    timestamp: MILESTONES.M1,
    improvement: "target range",
    referenceRange: { min: 60, max: 120 },
    optimalRange: { min: 70, max: 100 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },

  // Hormones
  {
    id: "hormones-total-t-m1",
    name: "Total Testosterone",
    value: 564,
    unit: "ng/dL",
    category: "hormones",
    subcategory: "sex" as any,
    timestamp: MILESTONES.M1,
    improvement: "higher is better",
    referenceRange: { min: 300, max: 1000 },
    optimalRange: { min: 500, max: 800 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "hormones-cortisol-m1",
    name: "Cortisol (AM)",
    value: 22,
    unit: "μg/dL",
    category: "hormones",
    subcategory: "cortisol" as any,
    timestamp: MILESTONES.M1,
    improvement: "target range",
    referenceRange: { min: 6.2, max: 19.4 },
    optimalRange: { min: 10, max: 18 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "hormones-tsh-m1",
    name: "TSH",
    value: 2.49,
    unit: "μIU/mL",
    category: "hormones",
    subcategory: "thyroid" as any,
    timestamp: MILESTONES.M1,
    improvement: "target range",
    referenceRange: { min: 0.4, max: 4.0 },
    optimalRange: { min: 1.0, max: 2.5 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },

  // Hematology
  {
    id: "hematology-wbc-m1",
    name: "WBC",
    value: 5.07,
    unit: "K/μL",
    category: "hematology",
    subcategory: "wbc" as any,
    timestamp: MILESTONES.M1,
    improvement: "target range",
    referenceRange: { min: 4.5, max: 11 },
    optimalRange: { min: 4.5, max: 7.5 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "hematology-rbc-m1",
    name: "RBC",
    value: 4.24,
    unit: "M/μL",
    category: "hematology",
    subcategory: "cbc" as any,
    timestamp: MILESTONES.M1,
    improvement: "target range",
    referenceRange: { min: 4.5, max: 5.9 },
    optimalRange: { min: 4.5, max: 5.5 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "hematology-hemoglobin-m1",
    name: "Hemoglobin",
    value: 13.8,
    unit: "g/dL",
    category: "hematology",
    subcategory: "hemoglobin" as any,
    timestamp: MILESTONES.M1,
    improvement: "target range",
    referenceRange: { min: 13.5, max: 17.5 },
    optimalRange: { min: 14.0, max: 16.5 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "hematology-hematocrit-m1",
    name: "Hematocrit",
    value: 40.9,
    unit: "%",
    category: "hematology",
    subcategory: "cbc" as any,
    timestamp: MILESTONES.M1,
    improvement: "target range",
    referenceRange: { min: 38, max: 50 },
    optimalRange: { min: 42, max: 48 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "hematology-platelets-m1",
    name: "Platelets",
    value: 184,
    unit: "K/μL",
    category: "hematology",
    subcategory: "platelets" as any,
    timestamp: MILESTONES.M1,
    improvement: "target range",
    referenceRange: { min: 150, max: 400 },
    optimalRange: { min: 200, max: 300 },
    source: "bloodwork",
    syncStatus: "local",
    syncVersion: 1,
  },
];

// Body Composition (DEXA) - M1, M2, M3
export const realBodyComposition: Metric[] = [
  // M1 - Feb 2025
  {
    id: "body-weight-m1",
    name: "Weight",
    value: 210.69,
    unit: "lbs",
    category: "bodyComposition",
    subcategory: "fat" as any,
    timestamp: MILESTONES.M1,
    improvement: "target range",
    referenceRange: { min: 180, max: 230 },
    optimalRange: { min: 195, max: 215 },
    source: "dexa",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "body-fat-pct-m1",
    name: "Body Fat",
    value: 27.3,
    unit: "%",
    category: "bodyComposition",
    subcategory: "fat" as any,
    timestamp: MILESTONES.M1,
    improvement: "lower is better",
    referenceRange: { min: 10, max: 30 },
    optimalRange: { min: 12, max: 20 },
    source: "dexa",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "body-lean-mass-m1",
    name: "Lean Mass",
    value: 153.13,
    unit: "lbs",
    category: "bodyComposition",
    subcategory: "leanMass" as any,
    timestamp: MILESTONES.M1,
    improvement: "higher is better",
    referenceRange: { min: 140, max: 180 },
    optimalRange: { min: 160, max: 175 },
    source: "dexa",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "body-vat-m1",
    name: "Visceral Fat (VAT)",
    value: 993,
    unit: "g",
    category: "bodyComposition",
    subcategory: "fat" as any,
    timestamp: MILESTONES.M1,
    improvement: "lower is better",
    referenceRange: { min: 0, max: 1500 },
    optimalRange: { min: 0, max: 500 },
    source: "dexa",
    syncStatus: "local",
    syncVersion: 1,
  },

  // M2 - May 2025
  {
    id: "body-weight-m2",
    name: "Weight",
    value: 215.04,
    unit: "lbs",
    category: "bodyComposition",
    subcategory: "fat" as any,
    timestamp: MILESTONES.M2,
    improvement: "target range",
    referenceRange: { min: 180, max: 230 },
    optimalRange: { min: 195, max: 215 },
    source: "dexa",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "body-fat-pct-m2",
    name: "Body Fat",
    value: 22.6,
    unit: "%",
    category: "bodyComposition",
    subcategory: "fat" as any,
    timestamp: MILESTONES.M2,
    improvement: "lower is better",
    referenceRange: { min: 10, max: 30 },
    optimalRange: { min: 12, max: 20 },
    source: "dexa",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "body-lean-mass-m2",
    name: "Lean Mass",
    value: 166.36,
    unit: "lbs",
    category: "bodyComposition",
    subcategory: "leanMass" as any,
    timestamp: MILESTONES.M2,
    improvement: "higher is better",
    referenceRange: { min: 140, max: 180 },
    optimalRange: { min: 160, max: 175 },
    source: "dexa",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "body-vat-m2",
    name: "Visceral Fat (VAT)",
    value: 810,
    unit: "g",
    category: "bodyComposition",
    subcategory: "fat" as any,
    timestamp: MILESTONES.M2,
    improvement: "lower is better",
    referenceRange: { min: 0, max: 1500 },
    optimalRange: { min: 0, max: 500 },
    source: "dexa",
    syncStatus: "local",
    syncVersion: 1,
  },

  // M3 - Sep 2025
  {
    id: "body-weight-m3",
    name: "Weight",
    value: 208.74,
    unit: "lbs",
    category: "bodyComposition",
    subcategory: "fat" as any,
    timestamp: MILESTONES.M3,
    improvement: "target range",
    referenceRange: { min: 180, max: 230 },
    optimalRange: { min: 195, max: 215 },
    source: "dexa",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "body-fat-pct-m3",
    name: "Body Fat",
    value: 22.5,
    unit: "%",
    category: "bodyComposition",
    subcategory: "fat" as any,
    timestamp: MILESTONES.M3,
    improvement: "lower is better",
    referenceRange: { min: 10, max: 30 },
    optimalRange: { min: 12, max: 20 },
    source: "dexa",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "body-lean-mass-m3",
    name: "Lean Mass",
    value: 161.83,
    unit: "lbs",
    category: "bodyComposition",
    subcategory: "leanMass" as any,
    timestamp: MILESTONES.M3,
    improvement: "higher is better",
    referenceRange: { min: 140, max: 180 },
    optimalRange: { min: 160, max: 175 },
    source: "dexa",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "body-vat-m3",
    name: "Visceral Fat (VAT)",
    value: 702,
    unit: "g",
    category: "bodyComposition",
    subcategory: "fat" as any,
    timestamp: MILESTONES.M3,
    improvement: "lower is better",
    referenceRange: { min: 0, max: 1500 },
    optimalRange: { min: 0, max: 500 },
    source: "dexa",
    syncStatus: "local",
    syncVersion: 1,
  },
];

// WHOOP Biometrics - Milestone averages from vault M3 comparison table
export const realAutonomicData: Metric[] = [
  // M1 - Feb 2025 (baseline)
  {
    id: "autonomic-hrv-m1",
    name: "HRV (RMSSD)",
    value: 32.4,
    unit: "ms",
    category: "autonomic",
    subcategory: "hrv" as any,
    timestamp: MILESTONES.M1,
    improvement: "higher is better",
    referenceRange: { min: 20, max: 100 },
    optimalRange: { min: 40, max: 70 },
    source: "whoop",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "autonomic-rhr-m1",
    name: "Resting Heart Rate",
    value: 57.3,
    unit: "BPM",
    category: "autonomic",
    subcategory: "hrv" as any,
    timestamp: MILESTONES.M1,
    improvement: "lower is better",
    referenceRange: { min: 50, max: 80 },
    optimalRange: { min: 50, max: 60 },
    source: "whoop",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "autonomic-recovery-m1",
    name: "Recovery Score",
    value: 48,
    unit: "%",
    category: "autonomic",
    subcategory: "recovery" as any,
    timestamp: MILESTONES.M1,
    improvement: "higher is better",
    referenceRange: { min: 0, max: 100 },
    optimalRange: { min: 66, max: 100 },
    source: "whoop",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "autonomic-sleep-m1",
    name: "Sleep Duration",
    value: 6.7,
    unit: "hrs",
    category: "autonomic",
    subcategory: "sleep" as any,
    timestamp: MILESTONES.M1,
    improvement: "target range",
    referenceRange: { min: 6, max: 9 },
    optimalRange: { min: 7, max: 8.5 },
    source: "whoop",
    syncStatus: "local",
    syncVersion: 1,
  },

  // M2 - May 2025
  {
    id: "autonomic-hrv-m2",
    name: "HRV (RMSSD)",
    value: 29.2,
    unit: "ms",
    category: "autonomic",
    subcategory: "hrv" as any,
    timestamp: MILESTONES.M2,
    improvement: "higher is better",
    referenceRange: { min: 20, max: 100 },
    optimalRange: { min: 40, max: 70 },
    source: "whoop",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "autonomic-rhr-m2",
    name: "Resting Heart Rate",
    value: 48.9,
    unit: "BPM",
    category: "autonomic",
    subcategory: "hrv" as any,
    timestamp: MILESTONES.M2,
    improvement: "lower is better",
    referenceRange: { min: 50, max: 80 },
    optimalRange: { min: 50, max: 60 },
    source: "whoop",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "autonomic-recovery-m2",
    name: "Recovery Score",
    value: 61.9,
    unit: "%",
    category: "autonomic",
    subcategory: "recovery" as any,
    timestamp: MILESTONES.M2,
    improvement: "higher is better",
    referenceRange: { min: 0, max: 100 },
    optimalRange: { min: 66, max: 100 },
    source: "whoop",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "autonomic-sleep-m2",
    name: "Sleep Duration",
    value: 6.8,
    unit: "hrs",
    category: "autonomic",
    subcategory: "sleep" as any,
    timestamp: MILESTONES.M2,
    improvement: "target range",
    referenceRange: { min: 6, max: 9 },
    optimalRange: { min: 7, max: 8.5 },
    source: "whoop",
    syncStatus: "local",
    syncVersion: 1,
  },

  // M3 - Aug/Sep 2025 (peak optimization)
  {
    id: "autonomic-hrv-m3",
    name: "HRV (RMSSD)",
    value: 43,
    unit: "ms",
    category: "autonomic",
    subcategory: "hrv" as any,
    timestamp: MILESTONES.M3,
    improvement: "higher is better",
    referenceRange: { min: 20, max: 100 },
    optimalRange: { min: 40, max: 70 },
    source: "whoop",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "autonomic-rhr-m3",
    name: "Resting Heart Rate",
    value: 51,
    unit: "BPM",
    category: "autonomic",
    subcategory: "hrv" as any,
    timestamp: MILESTONES.M3,
    improvement: "lower is better",
    referenceRange: { min: 50, max: 80 },
    optimalRange: { min: 50, max: 60 },
    source: "whoop",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "autonomic-recovery-m3",
    name: "Recovery Score",
    value: 78.5,
    unit: "%",
    category: "autonomic",
    subcategory: "recovery" as any,
    timestamp: MILESTONES.M3,
    improvement: "higher is better",
    referenceRange: { min: 0, max: 100 },
    optimalRange: { min: 66, max: 100 },
    source: "whoop",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "autonomic-sleep-m3",
    name: "Sleep Duration",
    value: 7.2,
    unit: "hrs",
    category: "autonomic",
    subcategory: "sleep" as any,
    timestamp: MILESTONES.M3,
    improvement: "target range",
    referenceRange: { min: 6, max: 9 },
    optimalRange: { min: 7, max: 8.5 },
    source: "whoop",
    syncStatus: "local",
    syncVersion: 1,
  },

  // M4 - Jan 2026 (current - cessation acute phase)
  {
    id: "autonomic-hrv-m4",
    name: "HRV (RMSSD)",
    value: 33.7,
    unit: "ms",
    category: "autonomic",
    subcategory: "hrv" as any,
    timestamp: MILESTONES.CURRENT,
    improvement: "higher is better",
    referenceRange: { min: 20, max: 100 },
    optimalRange: { min: 40, max: 70 },
    source: "whoop",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "autonomic-rhr-m4",
    name: "Resting Heart Rate",
    value: 55,
    unit: "BPM",
    category: "autonomic",
    subcategory: "hrv" as any,
    timestamp: MILESTONES.CURRENT,
    improvement: "lower is better",
    referenceRange: { min: 50, max: 80 },
    optimalRange: { min: 50, max: 60 },
    source: "whoop",
    syncStatus: "local",
    syncVersion: 1,
  },
  {
    id: "autonomic-recovery-m4",
    name: "Recovery Score",
    value: 58.6,
    unit: "%",
    category: "autonomic",
    subcategory: "recovery" as any,
    timestamp: MILESTONES.CURRENT,
    improvement: "higher is better",
    referenceRange: { min: 0, max: 100 },
    optimalRange: { min: 66, max: 100 },
    source: "whoop",
    syncStatus: "local",
    syncVersion: 1,
  },
];

// Combined function to get all real metrics
export function getRealMetrics(): Metric[] {
  return [
    ...realBloodWorkM1,
    ...realBloodWorkM2,
    ...realBodyComposition,
    ...realAutonomicData,
  ];
}

// Get latest value for each metric name
export function getLatestRealMetrics(): Metric[] {
  const all = getRealMetrics();
  const latestByName = new Map<string, Metric>();

  all.forEach((m) => {
    const existing = latestByName.get(m.name);
    if (!existing || new Date(m.timestamp) > new Date(existing.timestamp)) {
      latestByName.set(m.name, m);
    }
  });

  return Array.from(latestByName.values());
}
